services:
  - type: web
    name: invidious
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgres://使用者:密碼@主機:5432/資料庫名"
      - key: INVIDIOUS_DOMAIN
        value: "your-app-name.onrender.com"
      - key: VISITOR_DATA
        value: "dev"
      - key: PO_TOKEN
        value: "dev"
