services:
  - type: web
    name: invidious
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: "postgresql://invidious_db_s63e_user:LYoqbF56Whwf4SBuqSpyDmS5FvS1vpHE@dpg-d230grili9vc73a9d9kg-a/invidious_db_s63e"
      - key: INVIDIOUS_DOMAIN
        value: "your-app-name.onrender.com"
      - key: VISITOR_DATA
        value: "dev"
      - key: PO_TOKEN
        value: "dev"
